//! Simple JSON-file-based keystore for secp256k1 keypairs.
//!
//! Stores private keys generated by `getnewaddress` so that
//! `sendrawtransaction` can sign NEAR transactions on behalf of the user.
//!
//! Supports optional passphrase encryption using ChaCha20-Poly1305 (AEAD)
//! with 100k-round SHA256 KDF. Legacy XOR-encrypted wallets are read
//! transparently and re-encrypted with AEAD on next save.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::path::PathBuf;

#[derive(Serialize, Deserialize, Default)]
pub struct Keystore {
    keys: HashMap<String, KeyEntry>,
    /// Watch-only addresses (no private key, tracked for balance queries)
    #[serde(default)]
    watch_only: Vec<String>,
    /// If true, the wallet file on disk is encrypted
    #[serde(default)]
    pub encrypted: bool,
}

/// On-disk format for encrypted wallet (supports both legacy XOR and AEAD)
#[derive(Serialize, Deserialize)]
struct EncryptedWallet {
    encrypted: bool,
    salt: String, // hex-encoded 32-byte salt
    data: String, // hex-encoded encrypted data
    /// Legacy field: hex-encoded SHA256 of plaintext (XOR format only)
    #[serde(default)]
    check: String,
    /// New field: hex-encoded 12-byte nonce for ChaCha20-Poly1305
    #[serde(default)]
    nonce: String,
    /// Encryption scheme version: absent or "xor" = legacy, "aead" = ChaCha20-Poly1305
    #[serde(default)]
    scheme: String,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct KeyEntry {
    /// Hex-encoded 32-byte secp256k1 private key
    pub private_key_hex: String,
    /// Hex-encoded 33-byte compressed public key
    pub public_key_compressed_hex: String,
    /// Hex-encoded 64-byte uncompressed public key (no 0x04 prefix)
    pub public_key_uncompressed_hex: String,
}

/// Derive a key from passphrase + salt using iterated SHA256 (100k rounds)
fn derive_key(passphrase: &str, salt: &[u8]) -> [u8; 32] {
    let mut key = Sha256::new();
    key.update(passphrase.as_bytes());
    key.update(salt);
    let mut hash = key.finalize();

    for _ in 0..100_000 {
        let mut h = Sha256::new();
        h.update(&hash);
        h.update(salt);
        hash = h.finalize();
    }

    let mut result = [0u8; 32];
    result.copy_from_slice(&hash);
    result
}

/// Legacy XOR keystream encryption (kept for backward-compatible decryption only)
fn xor_encrypt(data: &[u8], key: &[u8; 32]) -> Vec<u8> {
    let mut result = Vec::with_capacity(data.len());
    let mut block = *key;
    let mut offset = 0;

    while offset < data.len() {
        for i in 0..32 {
            if offset + i >= data.len() {
                break;
            }
            result.push(data[offset + i] ^ block[i]);
        }
        offset += 32;
        // Next block
        let mut h = Sha256::new();
        h.update(&block);
        h.update(&key[..16]); // mix in part of original key
        let next = h.finalize();
        block.copy_from_slice(&next);
    }

    result
}

impl Keystore {
    /// Load keystore from disk, or create empty if not found.
    pub fn load() -> Self {
        let path = Self::path();
        match std::fs::read_to_string(&path) {
            Ok(contents) => {
                // Try to parse as encrypted wallet first
                if let Ok(enc) = serde_json::from_str::<EncryptedWallet>(&contents) {
                    if enc.encrypted {
                        // Return an empty keystore marked as encrypted
                        // The real keys will be loaded when walletpassphrase is called
                        return Keystore {
                            keys: HashMap::new(),
                            watch_only: Vec::new(),
                            encrypted: true,
                        };
                    }
                }
                // Try as plain keystore
                match serde_json::from_str(&contents) {
                    Ok(ks) => ks,
                    Err(e) => {
                        eprintln!("WARNING: wallet.json exists but contains invalid JSON ({}), starting with empty keystore", e);
                        Keystore::default()
                    }
                }
            }
            Err(_) => Keystore::default(),
        }
    }

    /// Load keystore with passphrase decryption.
    /// Supports both legacy XOR and new ChaCha20-Poly1305 AEAD formats.
    pub fn load_encrypted(passphrase: &str) -> Result<Self, String> {
        let path = Self::path();
        let contents = std::fs::read_to_string(&path)
            .map_err(|e| format!("Failed to read wallet file: {}", e))?;

        let enc: EncryptedWallet = serde_json::from_str(&contents)
            .map_err(|_| "Wallet file is not encrypted".to_string())?;

        if !enc.encrypted {
            return Err("Wallet is not encrypted".to_string());
        }

        let salt = hex::decode(&enc.salt).map_err(|_| "Invalid salt in wallet file".to_string())?;
        let encrypted_data = hex::decode(&enc.data)
            .map_err(|_| "Invalid encrypted data in wallet file".to_string())?;

        let key = derive_key(passphrase, &salt);

        let plaintext = if enc.scheme == "aead" {
            // New AEAD format: ChaCha20-Poly1305
            Self::decrypt_aead(&key, &enc.nonce, &encrypted_data)?
        } else {
            // Legacy XOR format: decrypt and verify checksum
            let decrypted = xor_encrypt(&encrypted_data, &key);
            let actual_check = hex::encode(Sha256::digest(&decrypted));
            if actual_check != enc.check {
                return Err("Incorrect passphrase".to_string());
            }
            decrypted
        };

        let json_str = String::from_utf8(plaintext)
            .map_err(|_| "Incorrect passphrase (invalid UTF-8)".to_string())?;

        let mut ks: Keystore = serde_json::from_str(&json_str)
            .map_err(|_| "Incorrect passphrase (invalid JSON)".to_string())?;
        ks.encrypted = true;
        Ok(ks)
    }

    /// Save keystore to disk with restrictive permissions (0o600).
    pub fn save(&self) -> Result<(), String> {
        let path = Self::path();
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("Failed to create keystore directory: {}", e))?;
        }
        let json = serde_json::to_string_pretty(self)
            .map_err(|e| format!("Failed to serialize keystore: {}", e))?;
        Self::write_with_restricted_permissions(&path, json.as_bytes())?;
        Ok(())
    }

    /// Save keystore encrypted with passphrase using ChaCha20-Poly1305 (AEAD).
    pub fn save_encrypted(&self, passphrase: &str) -> Result<(), String> {
        let path = Self::path();
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("Failed to create keystore directory: {}", e))?;
        }

        // Generate random salt and nonce using OsRng
        use rand::RngCore;
        let mut salt = [0u8; 32];
        let mut nonce_bytes = [0u8; 12];
        rand::rngs::OsRng.fill_bytes(&mut salt);
        rand::rngs::OsRng.fill_bytes(&mut nonce_bytes);

        // Serialize the inner keystore (without encrypted flag)
        let inner = Keystore {
            keys: self.keys.clone(),
            watch_only: self.watch_only.clone(),
            encrypted: false,
        };
        let plaintext = serde_json::to_string(&inner)
            .map_err(|e| format!("Failed to serialize keystore: {}", e))?;

        let key = derive_key(passphrase, &salt);
        let encrypted_data = Self::encrypt_aead(&key, &nonce_bytes, plaintext.as_bytes())?;

        let enc = EncryptedWallet {
            encrypted: true,
            salt: hex::encode(salt),
            data: hex::encode(encrypted_data),
            check: String::new(), // unused in AEAD scheme
            nonce: hex::encode(nonce_bytes),
            scheme: "aead".to_string(),
        };

        let json = serde_json::to_string_pretty(&enc)
            .map_err(|e| format!("Failed to serialize encrypted wallet: {}", e))?;
        Self::write_with_restricted_permissions(&path, json.as_bytes())?;
        Ok(())
    }

    /// Encrypt using ChaCha20-Poly1305 (authenticated encryption).
    fn encrypt_aead(key: &[u8; 32], nonce: &[u8; 12], plaintext: &[u8]) -> Result<Vec<u8>, String> {
        use chacha20poly1305::aead::{Aead, KeyInit};
        use chacha20poly1305::{ChaCha20Poly1305, Nonce};

        let cipher = ChaCha20Poly1305::new(key.into());
        let nonce = Nonce::from_slice(nonce);
        cipher
            .encrypt(nonce, plaintext)
            .map_err(|e| format!("Encryption failed: {}", e))
    }

    /// Decrypt using ChaCha20-Poly1305 (authenticated encryption).
    fn decrypt_aead(
        key: &[u8; 32],
        nonce_hex: &str,
        ciphertext: &[u8],
    ) -> Result<Vec<u8>, String> {
        use chacha20poly1305::aead::{Aead, KeyInit};
        use chacha20poly1305::{ChaCha20Poly1305, Nonce};

        let nonce_bytes =
            hex::decode(nonce_hex).map_err(|_| "Invalid nonce in wallet file".to_string())?;
        if nonce_bytes.len() != 12 {
            return Err("Invalid nonce length".to_string());
        }

        let cipher = ChaCha20Poly1305::new(key.into());
        let nonce = Nonce::from_slice(&nonce_bytes);
        cipher
            .decrypt(nonce, ciphertext)
            .map_err(|_| "Incorrect passphrase".to_string())
    }

    /// Insert a key entry for a Bitcoin address.
    pub fn insert(&mut self, address: String, entry: KeyEntry) {
        self.keys.insert(address, entry);
    }

    /// Get a key entry by Bitcoin address.
    pub fn get(&self, address: &str) -> Option<&KeyEntry> {
        self.keys.get(address)
    }

    /// List all addresses in the keystore.
    pub fn addresses(&self) -> Vec<&String> {
        self.keys.keys().collect()
    }

    /// Check if the keystore has any keys loaded
    pub fn is_empty(&self) -> bool {
        self.keys.is_empty()
    }

    /// Add a watch-only address (no private key needed).
    pub fn add_watch_only(&mut self, address: String) {
        if !self.watch_only.contains(&address) {
            self.watch_only.push(address);
        }
    }

    /// Get all watch-only addresses.
    pub fn watch_only_addresses(&self) -> &[String] {
        &self.watch_only
    }

    /// Check if an address is watch-only.
    pub fn is_watch_only(&self, address: &str) -> bool {
        self.watch_only.iter().any(|a| a == address)
    }

    /// Get all tracked addresses (keys + watch-only).
    pub fn all_addresses(&self) -> Vec<String> {
        let mut addrs: Vec<String> = self.keys.keys().cloned().collect();
        for wo in &self.watch_only {
            if !addrs.contains(wo) {
                addrs.push(wo.clone());
            }
        }
        addrs
    }

    /// Create an empty locked keystore (for post-lock state)
    pub fn empty_encrypted() -> Self {
        Keystore {
            keys: HashMap::new(),
            watch_only: Vec::new(),
            encrypted: true,
        }
    }

    /// Write data to a file with owner-only permissions (0o600 on Unix).
    fn write_with_restricted_permissions(
        path: &std::path::Path,
        data: &[u8],
    ) -> Result<(), String> {
        #[cfg(unix)]
        {
            use std::io::Write;
            use std::os::unix::fs::OpenOptionsExt;
            let mut file = std::fs::OpenOptions::new()
                .write(true)
                .create(true)
                .truncate(true)
                .mode(0o600)
                .open(path)
                .map_err(|e| format!("Failed to write wallet file: {}", e))?;
            file.write_all(data)
                .map_err(|e| format!("Failed to write wallet file: {}", e))?;
        }
        #[cfg(not(unix))]
        {
            std::fs::write(path, data)
                .map_err(|e| format!("Failed to write wallet file: {}", e))?;
        }
        Ok(())
    }

    fn path() -> PathBuf {
        let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
        PathBuf::from(home).join(".bitinfinity").join("wallet.json")
    }
}

impl KeyEntry {
    /// Get the 32-byte private key bytes.
    pub fn private_key_bytes(&self) -> Result<[u8; 32], String> {
        let bytes = hex::decode(&self.private_key_hex)
            .map_err(|e| format!("Invalid private key hex: {}", e))?;
        if bytes.len() != 32 {
            return Err("Private key must be 32 bytes".to_string());
        }
        let mut arr = [0u8; 32];
        arr.copy_from_slice(&bytes);
        Ok(arr)
    }

    /// Get the 64-byte uncompressed public key bytes (no 0x04 prefix).
    pub fn public_key_uncompressed_bytes(&self) -> Result<[u8; 64], String> {
        let bytes = hex::decode(&self.public_key_uncompressed_hex)
            .map_err(|e| format!("Invalid public key hex: {}", e))?;
        if bytes.len() != 64 {
            return Err("Uncompressed public key must be 64 bytes".to_string());
        }
        let mut arr = [0u8; 64];
        arr.copy_from_slice(&bytes);
        Ok(arr)
    }

    /// Format the public key as NEAR's "secp256k1:<base58>" string.
    pub fn near_public_key_string(&self) -> Result<String, String> {
        let bytes = self.public_key_uncompressed_bytes()?;
        Ok(format!("secp256k1:{}", bs58::encode(&bytes).into_string()))
    }
}
